services:
  core-api:
    build:
      context: .
      dockerfile: ./docker/core-api.Dockerfile
    ports: 
      - "7171:7171"

  viewer:
    build:
      context: .
      dockerfile: ./docker/viewer.Dockerfile
    ports:
     - "4200:80"
    depends_on:
      - core-api
