#Create
POST http://localhost:7171/door/api/v1/applications

{
    "url": "http://localhost:8080",
    "country": "brasil"
}

#Get all
GET http://localhost:7171/door/api/v1/applications

#Get by id
GET http://localhost:7171/door/api/v1/applications/10


#Delete by id
DELETE http://localhost:7171/door/api/v1/applications/2