# Register
POST http://localhost:7171/api/v1/auth/register

{
    "username": "door-admin",
    "email": "admin@gmail.com",
    "password": "1234567890"
}

# Login
POST http://localhost:7171/api/v1/auth/login

{
    "username": "door-admin",
    //"email": "admin@gmail.com",
    "password": "1234567890"
}

# Token
GET http://localhost:7171/api/v1/auth/token