name: test core with python

on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.2"

      - name: Gen random dotenv
        run: |
          echo "JWT_ACCESS_TOKEN_SECRET=$(openssl rand -hex 32)" >> .env
          echo "JWT_REFRESH_TOKEN_SECRET=$(openssl rand -hex 64)" >> .env
          echo "BASE_URL=http://localhost:7171" >> .env
          echo "MAX_ATTEMPTS=50" >> .env
          echo "TIMEOUT=5" >> .env
          echo "ALLOWED_ORIGINS=http://localhost:4200,http://localhost:3000" >> .env
          echo "DB_PATH=./database.db" >> .env

      - name: Debug .env
        run: cat .env

      - name: Dependency download
        run: go mod tidy

      - name: Run core (background)
        run: |
          nohup go run cmd/api/main.go > core.log 2>&1 &
          echo $! > core.pid

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14.3"
      
      - name: Install Dependency
        working-directory: tests/
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check sqlite file
        run: |
          find . -maxdepth 3 -type f -name "*.db"
          ls -la

      - name: Wait API ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:7171/proxy/ > /dev/null; then
              echo "API is ready!"
              exit 0
            fi
            echo "Waiting API..."
            sleep 1
          done

          echo "API did not start in time"
          cat core.log || true
          exit 1

      - name: Run Python
        working-directory: tests/
        run: |
          python main.py
      
      - name: Stop core
        if: always()
        run: |
          kill $(cat core.pid) || true